# Generated by Django 4.2.27 on 2025-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('certificate_hash', models.CharField(max_length=256)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
